### PR TITLE
Fixed scalestatus plugin to match master Lite XL core

### PR DESCRIPTION
**Pull request by adamharrison**
Do not merge this PR until the next Lite XL release, which has the scale plugin has been fully integrated into the core.

### CODE REVIEW

**Comment by franko** [comment]
Shouldn't we merge this into a specific branch for the next release ? This way we just merge the branch when we make the new release and we are done.

**Comment by adamharrison** [comment]
Sure; I was just planning to leave this open until that next release, realistically (as the ScaleStatus branch on my repo), but I'm open to doing it however you like. Did you want me to create a branch on the plugin repo itself that just basically contains all changes that'll take effect come 2.0?

**Comment by adamharrison** [comment]
On a related note, do you think you could give me write access to this repo? If that's the way you want to go, it would let me set up the 2.0 branch directly on here.

**Comment by franko** [comment]
> On a related note, do you think you could give me write access to this repo? If that's the way you want to go, it would let me set up the 2.0 branch directly on here.

You have a pending invitation since a long time. I think you overlooked the notification.

**Comment by adamharrison** [comment]
Ah, yes. Can you send me another? They expire after 7 days. Sorry about that.

**Comment by adamharrison** [comment]
OK, this has been thrown into the 2.0 branch.

**Pull request closed without merging**
