### PR TITLE
Minimap Plugin

### PR DESCRIPTION
**Pull request by adamharrison**
Ripped https://github.com/andsve/lite-plugins/tree/minimap-plugin from their pull request for normal Lite.

It seems to work fine in Lite XL; and I feel like this is something a lot of editors have these days. Definitely shouldn't be a default plugin, but as a plugin in a repo, makes huge sense to me.

### CODE REVIEW

**Comment by adamharrison** [comment]
Perhaps we should read out and ask @andsve directly, though, before merging this in if he wouldn't mind us adding it here.

**Comment by adamharrison** [comment]
By the way, should close https://github.com/lite-xl/lite-xl/issues/156.

**Comment by andsve** [comment]
Hey, thanks for the ping :+1: No problem with me, happy it will be used.

**Comment by Atreyu-94** [comment]
Any progress around here? It would be great to have it as a plugin in version 2.0 :)

**Comment by adamharrison** [comment]
Yeah; forgot about this. I have merge powers now. I think this is good, and doesn't depend on anything coming up in 2.0 to be merged. So... it's in!

**Comment by Atreyu-94** [comment]
Cool! I thought It was stopped for some review issue :D

**Pull request merged**
