### PR TITLE
Rewrite ephemeral tabs plugin

### PR DESCRIPTION
**Pull request by Jipok**
Excellent concept. I've used this a lot in vscode.
But I don't understand how to use it without the ability to easily turn the doc into a regular one. With this, double-clicking either on a tab or on a file in TreeView will make the doc not ephemeral.

I also reduced the ephemeral notation from two characters`--` to one`~`. Although vscode uses an italic font for this, it seems like it won't be easy to repeat.

### CODE REVIEW

**Comment by Guldoman** [comment]
> I also reduced the ephemeral notation from two characters`--` to one`~`. Although vscode uses an italic font for this, it seems like it won't be easy to repeat.

You could try to override `Node:draw_tab`, so that when called you switch `style.font` with an italicized version, then call the original `Node:draw_tab`, then restore `style.font`.
The main problem is that the only way to check if the tab should be italicized is via the `text` parameter, which could raise problems.
Maybe we should pass the entire `View` to `draw_tab`, so that plugins can have more info about the tab "owner".
Splitting the `draw_tab` function (like in lite-xl/lite-xl#708) might also be a good idea.

**Comment by adamharrison** [comment]
> But I don't understand how to use it without the ability to easily turn the doc into a regular one. With this, double-clicking either on a tab or on a file in TreeView will make the doc not ephemeral.

I think on doc change it makes it non-ephemeral, no? So you just have to type something, I thought.

But yeah; this change is a good one. I like it.

**Comment by Guldoman** [comment]
It looks like double clicking on a tab doesn't remove the ephemeral status.

This is not a problem introduced by this PR, but creating new docs gives them the ephemeral status, but it's not really respected.

Also, what do you think about making it so that even the first opened file is ephemeral?

**Comment by Jipok** [comment]
> I think on doc change it makes it non-ephemeral, no? So you just have to type something, I thought.

True, but very inconvenient and annoying. I often open multiple files just for viewing, but I need to type something and then undo, otherwise it will be replaced with the next file. Annoys.

> It looks like double clicking on a tab doesn't remove the ephemeral status.
> creating new docs gives them the ephemeral status, but it's not really respected.

I don't know, it works for me. Maybe you have some kind of conflict with other plugins?
Or i have. I'll check it on clean build a little later.

https://user-images.githubusercontent.com/25588359/145672175-d1002451-b6e0-4a94-8c00-ae4e21f10fa0.mp4

> Also, what do you think about making it so that even the first opened file is ephemeral?

I thought it was. I checked you are right. I will make it so. It is better and consistency.

**Comment by Guldoman** [comment]
> > It looks like double clicking on a tab doesn't remove the ephemeral status.
> 
> I don't know, it works for me. Maybe you have some kind of conflict with other plugins? Or i have. I'll check it on clean build a little later.

It looks like it does indeed work on `master`, but not on `2.0.3`.

**Comment by Jipok** [comment]
> You could try to override Node:draw_tab, so that when called you switch style.font with an italicized version, then call the original Node:draw_tab, then restore style.font.

The node is a local object of `rootview.lua` and is not returned by the module. I have a little bit forgotten lua, but it seems its methods cannot be overridden.

**Comment by Jipok** [comment]
I rewrote the plugin. The old logic seemed a little confusing and redundant to me. It also performed very poorly with split view.
I had some ideas, but they required overloading `Node`(rootview.lua) methods. I don't know how to do this, which is why the final version turned out to be different.

**Comment by adamharrison** [comment]
Wait; but doesn't this now not make things non-ephemeral upon edit? Could we restore that functionality?

**Comment by Guldoman** [comment]
Is renaming the plugin the correct way to go? Users of the current plugin that used a symlink to install it, won't have it working without manual intervention.

**Comment by adamharrison** [comment]
On one hand, it's probably best to not rename things unnecessarily; on the other hand, this is a non-core plugin; I doubt it honestly has that many users. `ephemral_tabs` is more clear, generally. 

I'm OK with either.

**Comment by Guldoman** [comment]
> The node is a local object of `rootview.lua` and is not returned by the module. I have a little bit forgotten lua, but it seems its methods cannot be overridden.

You're right, I was already thinking about lite-xl/lite-xl#715.

> How soon is the next release?

The next release will be a bugfix release `2.0.4`, where I suspect this still wouldn't work.

**Comment by Guldoman** [comment]
> `ephemral_tabs` is more clear, generally.
> I'm OK with either.

Then also the `README` should be changed.

**Comment by adamharrison** [comment]
> Then also the README should be changed.

Agreed.

**Comment by adamharrison** [comment]
Oh, one last thing; can you make sure you return true from any mouse-clicking functions? That's one of the things causing the issues in https://github.com/lite-xl/lite-xl/issues/723.

**Comment by Jipok** [comment]
In an amicable way, it would be necessary to override file opening only for TreeView. Files opened through ctrl-o should not be ephemeral.
But I think this will not be achieved without changing the treeview.lua code. So not for this PR.

**Comment by Guldoman** [comment]
> In an amicable way, it would be necessary to override file opening only for TreeView. Files opened through ctrl-o should not be ephemeral. But I think this will not be achieved without changing the treeview.lua code. So not for this PR.

You could do something like
```lua
local ephemeral = false

local RootView_open_doc = RootView.open_doc
function RootView:open_doc(doc)
  local docview = RootView_open_doc(self, doc)
  if ephemeral then
    print("Do thing here")
  end
  return docview
end

local on_mouse_pressed = TreeView.on_mouse_pressed
function TreeView:on_mouse_pressed(button, x, y, clicks)
  ephemeral = true
  local result = on_mouse_pressed(self, button, x, y, clicks)
  ephemeral = false
  return result
end
```

**Pull request merged**
