### PR TITLE
Add file icons set for TreeView

### PR DESCRIPTION
**Pull request by Jipok**
image

The icons and colors are taken from here:
https://github.com/yamatsum/nvim-nonicons

I did not add all the possible icons, because I am too lazy and I realized that the selected font is not so good and rich. Maybe it should be redone to nerd font. 
It might be worth adding support for icons to the main code. I don't like the concept of overriding a method as large as TreeView:draw. 

To install, you need to [download the font](https://github.com/yamatsum/nonicons/raw/master/dist/nonicons.ttf) and put it in `DATADIR .. "/fonts/nonicons.ttf"`

### CODE REVIEW

**Comment by AqilCont** [comment]
I love the icons you have on by default :O
Can you provide the font somewhere too? So we don't have to make a custom one every time :D

**Comment by vincens2005** [comment]
This is super cool!

**Review by vincens2005 — APPROVED** [review]

**Comment by Guldoman** [comment]
I think this PR might be of interest to you: lite-xl/lite-xl#708

Also, this closes lite-xl/lite-xl#706

**Comment by Jipok** [comment]
> Can you provide the font somewhere on the README too? So no one has to unnecessarily look for it :D

It is actually easier and much more correct to use fontconfig. And let the user install the font however they want. But it seems that such a solution may not work on windows. I'm not sure.

**Comment by Jipok** [comment]
- Added more icons
- Tested how it looks with a white theme
- Fixed indentation between icon and chevron.
- The font is now loaded from the user folder (`~/.config/lite-xl`)

image

I am no longer overriding `style.icon_font` but using a local variable. Otherwise, after any reboot of the modules (for example, changing the user config) the standard font of the icons was loaded again and all the icons disappeared.

**Comment by Jipok** [comment]
I also had an idea with automatic downloading (via curl or vget) of the font if it is not there. But this approach may not be encouraged, and it is not clear which command to call in other operating systems.

**Comment by Jipok** [comment]
image

**Comment by jminor** [comment]
@Jipok after https://github.com/lite-xl/lite-xl/pull/708 lands, then you can override `get_item_icon` instead of the whole draw function. Like this:

```lua
function TreeView:get_item_icon(item, active, hovered)
  -- default icon
  local icon = "" -- unicode 61766
  local font = icon_font

  if item.type == "dir" then
    icon = item.expanded and "D" or "d"
    font = style.icon_font
  end

  local color = style.text
  if active or hovered then
    color = style.accent
  end

  -- icon depending on the file extension or full name
  local custom_icon = known_names_icons[item.name:lower()]
  if custom_icon == nil then
    custom_icon = extension_icons[item.name:match("^.+(%..+)$")]
  end
  if custom_icon ~= nil then
    color = custom_icon[1]
    icon = custom_icon[2]
    font = icon_font
  end
  
  return icon, font, color
end
```

**Comment by adamharrison** [comment]
@Jipok I think this is good; do you want me to merge this now, or do you want to target 2.1 with the new changes from #708?

**Comment by Jipok** [comment]
I thought it was already merged)
I did not notice that it does not support the current stable version. Fixed. Merge it, I'll make a separate pr for 2.1

**Pull request merged**
